/** @type {import('tailwindcss').Config} */
module.exports = {
  prefix: 'ussf-',
  content: [
    "./resources/views/**/*.blade.php",
    "./src/**/*.php",
  ],
  safelist: [
    // Button component classes
    'ussf-inline-flex',
    'ussf-items-center',
    'ussf-justify-center',
    'ussf-font-medium',
    'ussf-border',
    'ussf-transition-colors',
    'ussf-duration-200',
    'focus:ussf-outline-none',
    'focus:ussf-ring-2',
    'focus:ussf-ring-blue-500',
    'focus:ussf-ring-offset-2',
    'disabled:ussf-opacity-50',
    'disabled:ussf-cursor-not-allowed',
    'ussf-px-3',
    'ussf-py-1.5',
    'ussf-text-sm',
    'ussf-px-4',
    'ussf-py-2',
    'ussf-text-base',
    'ussf-px-6',
    'ussf-py-3',
    'ussf-text-lg',
    'ussf-ml-2',
    'ussf-mr-2',
    'ussf-bg-blue-600',
    'hover:ussf-bg-blue-700',
    'ussf-text-white',
    'ussf-border-transparent',
    'ussf-bg-gray-200',
    'hover:ussf-bg-gray-300',
    'ussf-text-gray-900',
    'ussf-bg-transparent',
    'hover:ussf-bg-gray-100',
    'ussf-text-gray-700',
    'ussf-border-gray-300',
    'ussf-rounded-full',
    'ussf-rounded-md',
    // Typography component classes
    'ussf-text-4xl',
    'ussf-font-bold',
    'ussf-leading-tight',
    'ussf-text-3xl',
    'ussf-text-2xl',
    'ussf-font-semibold',
    'ussf-text-xl',
    'ussf-font-medium',
    'ussf-leading-relaxed',
    'ussf-list-disc',
    'ussf-list-inside',
    'ussf-space-y-1',
    'ussf-list-decimal',
    // USSF colors
    'ussf-bg-ussf-blue-600',
    'ussf-bg-ussf-red-600',
    'ussf-text-ussf-blue-500',
    'ussf-text-ussf-red-500',
    'ussf-bg-ussf-blue-300',
    'ussf-bg-ussf-blue-500',
    'ussf-bg-ussf-blue-700',
    'ussf-bg-ussf-red-300',
    'ussf-bg-ussf-red-500',
    'ussf-bg-ussf-red-700',
    // Common utility classes
    'ussf-font-sans',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
        'ussf-blue': {
          100: '#e6f3ff',
          200: '#cce7ff',
          300: '#99d0ff',
          400: '#66b8ff',
          500: '#3399ff',
          600: '#0066cc',
          700: '#004499',
          800: '#003366',
          900: '#002244',
        },
        'ussf-red': {
          100: '#ffe6e6',
          200: '#ffcccc',
          300: '#ff9999',
          400: '#ff6666',
          500: '#ff3333',
          600: '#cc0000',
          700: '#990000',
          800: '#660000',
          900: '#440000',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
}